# Tệp cấu hình
# Đặt true hoặc false để bật hoặc tắt giữ đồ sau khi chết

KeepInventory: true

# Loại tin nhắn: chat, popup, tip, title

MessageType: chat

# Tin nhắn đồ của người chơi đã được giữ lại sau khi chết
# Dùng '&' để làm chữ màu

MessageAfterDeath: "&aĐồ của bạn đã được giữ"
